import React from 'react';
import {Alert, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import Header from '../components/Header';
import {COLORS, SHADOW} from '../theme';

const people=[['M','Maya','Daughter','Available to call'],['A','Arjun','Son','Available to call'],['M','Dr. Meera','Care Partner','Trusted contact']];
export default function CircleScreen({onBack}){return <View style={styles.screen}><Header onBack={onBack} title="Your Circle"/><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
 <View style={styles.banner}><View style={styles.bannerIcon}><Text style={styles.bannerIconText}>♥</Text></View><View style={{flex:1}}><Text style={styles.bannerTitle}>People who care about you</Text><Text style={styles.bannerSub}>Your trusted circle is close when you need them.</Text></View></View>
 <Text style={styles.section}>TRUSTED PEOPLE</Text>
 {people.map(([initial,name,role,status])=><View key={name} style={styles.person}><View style={styles.avatar}><Text style={styles.avatarText}>{initial}</Text></View><View style={{flex:1}}><Text style={styles.name}>{name}</Text><Text style={styles.role}>{role}</Text><Text style={styles.status}>{status}</Text></View><Pressable onPress={()=>Alert.alert('Demo call',`Calling ${name}...`)} style={styles.call}><Text style={styles.callText}>Call</Text></Pressable></View>)}
 <Pressable style={styles.add} onPress={()=>Alert.alert('Add person','This will be connected to the backend.') }><Text style={styles.addText}>＋ Add Trusted Person</Text></Pressable>
 </ScrollView></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:COLORS.background},content:{padding:16,paddingBottom:30},banner:{backgroundColor:COLORS.primaryDeep,borderRadius:21,padding:16,flexDirection:'row',alignItems:'center',...SHADOW},bannerIcon:{width:50,height:50,borderRadius:18,backgroundColor:'rgba(255,255,255,.13)',alignItems:'center',justifyContent:'center',marginRight:12},bannerIconText:{fontSize:23,color:COLORS.white},bannerTitle:{fontSize:16,fontWeight:'900',color:COLORS.white},bannerSub:{fontSize:10.5,color:COLORS.mint,marginTop:3,lineHeight:15},section:{fontSize:10,color:COLORS.primaryDark,fontWeight:'900',letterSpacing:1.2,marginTop:22,marginBottom:10},person:{backgroundColor:COLORS.white,borderRadius:18,padding:13,flexDirection:'row',alignItems:'center',marginBottom:10,...SHADOW},avatar:{width:52,height:52,borderRadius:26,backgroundColor:COLORS.primarySoft,alignItems:'center',justifyContent:'center',marginRight:11},avatarText:{fontSize:19,color:COLORS.primaryDark,fontWeight:'900'},name:{fontSize:15.5,fontWeight:'900',color:COLORS.text},role:{fontSize:11,color:COLORS.muted,marginTop:2},status:{fontSize:10,color:COLORS.success,fontWeight:'800',marginTop:3},call:{backgroundColor:COLORS.primary,borderRadius:12,paddingHorizontal:14,paddingVertical:9},callText:{color:COLORS.white,fontWeight:'900',fontSize:11},add:{height:54,borderRadius:17,borderWidth:1.5,borderColor:COLORS.primary,borderStyle:'dashed',alignItems:'center',justifyContent:'center',marginTop:2},addText:{color:COLORS.primaryDark,fontWeight:'900',fontSize:14}});
